services:
  - type: web
    name: zoomactu-bot-fastapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
